[build]
  command = "npm run build"
  publish = "dist"

# OTA update bundles - serve static files from /ota folder
[[redirects]]
  from = "/ota/*"
  to = "/ota/:splat"
  status = 200

# SPA fallback - must come after /ota/* rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"